### ISSUE TITLE
on datarmor : dupplication of OSmOSEanalytics_0.1.0/OSmOSEanalytics_0.1.0 on purpose ?

### ISSUE THREAD

**Issue by cazaudo** [Project-ODE/jupyter_scripts#31]
the folder seems to be replicated inside itself , is it on purpose ?
OSmOSEanalytics_0.1.0/OSmOSEanalytics_0.1.0

**Comment by Rumengol** [comment]
I noticed it too and don't know how it happened, but since it is only on datarmor I surmise we can safely remove the duplicate.
